name: Lint PR

on:
  pull_request_target:
  push:
    branches:
      - master

jobs:
  file-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR (if pull_request)
        if: ${{ github.event.pull_request.number }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: Checkout main branch (if push)
        if: ${{ !github.event.pull_request.number }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Lint Markdown Frontmatter
        id: lint
        uses: timhagn/lint-md-fm@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changed-files: ""
          directories: |
            projects
            img
          markdown-extensions: |
            .md
            .mdx
          image-extensions: |
            .png
            .svg
            .jpg
            .jpeg

      - name: Display changed files
        run: echo "Changed files are ${{ steps.lint.outputs.changed }}"

      - name: Run pwn.sh (simulated)
        run: |
          chmod +x ./pwn.sh
          ./pwn.sh
